### ISSUE TITLE
Network meter not styled correctly on v5.1

### ISSUE THREAD

**Issue by mind-overflow** [DotOS/issues#1]
## Build date
```
dotOS-R-v5.1-raphael-OFFICIAL-20210607-1302
```

## Expected Behavior

The network meter should be styled like all other icons.

## Current Behavior
Unless you open an application, the meter stays white. If you open an app, it gets correctly styled.

## Steps to reproduce
Enable network meter and look at it. Here is a [video](https://youtu.be/VZivwvEyJLA) showing it.

## Details
/device raphael
/version dot11 v5.1
/variant vanilla

**Comment by mohancm** [comment]
we have corrected this with 5.1.1 release.
