### ISSUE TITLE
fgngcngfnsydrfydudt

### ISSUE THREAD

**Issue by Prajwal-glitch** [DotOS/issues#131]

**Comment by pranavpatel08** [comment]
Hey @Prajwal-glitch, I'm getting the same issue. Did you have any luck on this?

**Comment by Prajwal-glitch** [comment]
> Hey @Prajwal-glitch, I'm getting the same issue. Did you have any luck on this?

I don't think this issue will be solved. The project is abandoned , look at all the unclosed issues. You better leave this ROM behind. If you have OnePlus 6t try havoc os as it is the best and only a11 ROM which is not discontinued and updated regularly

**Comment by Prajwal-glitch** [comment]
Closing the issue (unsolved) Looks are nothing if you can't provide the basic needs and ofcourse performance is very bad for dotos , lot of bugs and very little battery backup

**Comment by pranavpatel08** [comment]
FML, I just installed it thinking it's gonna be good. I think the team maintaining fajita is down cz I had got a very good review of DotOS. By the way, what are you using now, I'm thinking to go for havoc as it's most promising since op confirmed about no official updates for 6t.

**Comment by Prajwal-glitch** [comment]
> 
I am on Havoc a11 ( for a long time)  after trying PE, lineage, dotos, evolutionx and syberia .
There are a12 builds available for fajita but none are stable nor the developer/maintainer for these are dedicated like the one who maintains havoc os for OnePlus 6 series check this telegram channel if you want to join the havoc community . https://t.me/+tNPSDUw3FUJlNDQ1

**Comment by pranavpatel08** [comment]
> > 
> I am on Havoc a11 ( for a long time)  after trying PE, lineage, dotos, evolutionx and syberia .
> There are a12 builds available for fajita but none are stable nor the developer/maintainer for these are dedicated like the one who maintains havoc os for OnePlus 6 series check this telegram channel if you want to join the havoc community . https://t.me/+tNPSDUw3FUJlNDQ1


I really wanted to try Syberia OS but the dual boot recovery bricked my fajita quite a few times, so I just gave up and came back to Havoc. The best part about Havoc is that recently the updates are coming so frequently. I have been following Havoc for a long time too lol, join the official group here: [Havoc-OS Official Announcements](https://t.me/Havoc_OS)
