### ISSUE TITLE
why

### ISSUE THREAD

**Issue by ghost** [DotOS/issues#23]
vendor/qcom/opensource/commonsys/packages/apps/Bluetooth/jni/com_android_bluetooth_gatt.cpp:2315:21: error: no member named 'TransferSync' in 'BleScannerInterface'
sGattIf->scanner->TransferSync(str2addr(env,addr), service_data, sync_handle,

**Comment by mohancm** [comment]
fixed - https://github.com/DotOS/manifest/issues/21
