### ISSUE TITLE
Hello, I use a Galaxy A8 2018, and when I go to log into the google account, it simply goes to a black screen, closes and goes back to the Playstore login request screen

### ISSUE THREAD

**Issue by Vaz15k** [DotOS/issues#27]
## Build date

```
Example: dotOS-R-v5.0.1-mido-OFFICIAL-20210418-0725
```

## Expected Behavior

```
Edit here
```

## Current Behavior

```
Edit here
```

## Possible Solution

```
Edit here
```

## Steps to Reproduce

```
1.
2.
3.
4.
```

/device
/version
/variant

**Comment by mohancm** [comment]
this issue is incomplete. we don't know which build/version you're using. complete the following data to get help.
